<div>
    <a class="back-link" href="/item"><-terug</a>
</div>
<div class="cardbutton-container">
    <a href="/item/frontCard?id=<?= $this->data['id'] ?>">
        <button class="cardbutton">
            <span class="big-bold"><?= htmlspecialchars($this->data['result'][0]['ide']) ?></span>
            <br>
            <span class="small-thin"><?= htmlspecialchars($this->data['result'][0]['sde']) ?></span>
        </button>
    </a>
</div>
<div class="known-container">
    <a href="/item/frontCard?id=<?= $this->data['id'] ?>" class="known">
        <button class="known" type="submit" name="unknown">❌</button>
    </a>
    <a href="/item/frontCard" class="known">
        <button class="unknown" type="submit" name="known">✔️</button>
    </a>

</div>

