<div >
    <a class="back-link" href="/item"><-back</a>
</div>
<div class="cardbutton-container">
<a href="/item/backCard?id=<?= $this->data['id']?>">

    <button class="cardbutton" type="submit" name="backCard">
            <?= htmlspecialchars($this->data['resultItem'][0]['nl']) ?>
            <br>
            <?= htmlspecialchars($this->data['resultSentence'][0]['nl']) ?>
    </button>
</a>
</div>
