<div>
    <a class="back-link" href="/item"><-terug</a>
</div>
<div class="cardbutton-container">
    <a href="/item/backCard?id=<?= $this->data['id'] ?>">

        <button class="cardbutton" type="submit" name="backCard">
            <span class="big-bold"> <?= htmlspecialchars($this->data['result'][0]['inl']) ?></span>
            <br>
            <span class="small-thin"><?= htmlspecialchars($this->data['result'][0]['snl']) ?></span>
        </button>
    </a>
</div>
