<div class="logo-container">
    <img class="logo" src="Lijst_logo.png" alt="Image of Nachtmerrie">
</div>
<div class="button-container">
    <form action="/item/frontCard" method="post">
        <button class="actionButton">Woorden leren</button>
    </form>
    <a class="actionButton" href="/item/newItem">Nieuw Word</a>
    <form action="/item/newList" method="post">
        <button type="submit" class="actionButton">Nieuw Woordenlijst</button>
    </form>
</div>

<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>NL</th>gst
        <th>DE</th>
        <th> </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->data['result'] as $row): ?>
        <tr>
            <td><?= htmlspecialchars($row['id']) ?></td>
            <td><?= htmlspecialchars($row['nl']) ?></td>
            <td><?= htmlspecialchars($row['de']) ?></td>
            <td><form action="/item/delete" method="post">
                    <input type="hidden" name="delId" value="<?= htmlspecialchars($row['id']) ?>">
                    <button type="submit" name="delete" class="delItem">X</button>
                </form></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>