<div class="logo-container">
    <img class="logo" src="Lijst_logo.png" alt="Image of Nachtmerrie">
</div>
<!--<h1>--><?php //= $this->data['WL'] ?><!--</h1>-->
<div class="button-container">
    <form action="/item/frontCard" method="post">
        <button class="learnCards">Woorden leren</button>
    </form>
    <form action="/item/newList" method="post">
        <button type="submit" class="learnCards">Nieuw Woordenlijst</button>
    </form>
</div>
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>NL</th>gst
        <th>DE</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->data['result'] as $row): ?>
        <tr>
            <td><?= htmlspecialchars($row['id']) ?></td>
            <td><?= htmlspecialchars($row['nl']) ?></td>
            <td><?= htmlspecialchars($row['de']) ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>