<div>
    <a class="back-link" href="/item"><-back</a>
</div>
<h1 class="newWord">Voeg een nieuw woord in</h1>
<div class="container">
    <form action="/item/insert" method="post">

        <label for="nl">Nederlands:</label>
        <input type="text" id="nl" name="nl" required><br><br>

        <label for="nl_sentence">Nederlandse zin:</label>
        <input type="text" id="nl_sentence" name="nl_sentence" required><br><br>

        <label for="de">Duits:</label>
        <input type="text" id="de" name="de" required><br><br>

        <label for="de_sentence">Duitse zin:</label>
        <input type="text" id="de_sentence" name="de_sentence" required><br><br>

        <button type="submit" class="actionButton">opslaan</button>
    </form>
</div>
